/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.semantyca.srv.tests;

import static org.junit.Assert.assertTrue;

import org.junit.Test;

import com.semantyca.srv.App;

public class AppTest {
    @Test public void testAppHasAGreeting() {
        App classUnderTest = new App();
        assertTrue(true);
    }
}
